# Generated by Django 5.0 on 2024-08-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image_alter_project_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='images/800x600.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(default='videos/800x600.png', null=True, upload_to='videos/'),
        ),
    ]
