# Generated by Django 5.0 on 2024-08-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image_alter_project_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.FileField(default='800x600.png', null=True, upload_to='content/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='800x600.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(default='800x600.png', null=True, upload_to='videos/'),
        ),
    ]
