# Generated by Django 5.0 on 2024-08-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_mediacontent_alter_project_image_alter_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
